### ISSUE TITLE
vim is not preinstalled by default

### ISSUE THREAD

**Issue by ZeinBarhoum** [rakarmp/Linux-Commands-Guide#3]
Since most of the commands presented in this repository are preinstalled, I believe `vim` command should be replaces with the `vi` command since its existent with the OS just after installation is much more likely.

**Comment by rakarmp** [comment]
Thank you for your contribution and valuable input.

I have understood your request to replace the `vim` command with `vi` in the documentation. I would like to explain some considerations behind using `vim` in the documentation:

1. **Popularity of Vim**: Vim is a highly popular text editor in the Linux community and is widely used by users who leverage its advanced features.

2. **Ease of Understanding**: For users who might be newer to the Linux world, the distinction between `vi` and `vim` might not be clear. Referring to `vim` can help them understand more commands and features available.

3. **Common Usage**: While `vi` is often preinstalled, `vim` is also common and frequently comes preinstalled on many modern Linux distributions.

Taking these factors into account, I will continue to use `vim` in the documentation as it can provide a valuable resource for a wide range of Linux users, both experienced and newcomers.

Thank you for your understanding, and if you have any further input or questions, please feel free to ask.

**Comment by rakarmp** [comment]
> Since most of the commands presented in this repository are preinstalled, I believe `vim` command should be replaces with the `vi` command since its existent with the OS just after installation is much more likely.

Thank you for your feedback! After careful consideration, I decided to keep `vim` in the documentation for the reasons mentioned earlier. If you have any other questions or suggestions, please feel free to contact me. Your contributions are greatly appreciated!

**Comment by ZeinBarhoum** [comment]
It was just a suggestion, after all `vim` is one of my favorite editors!
Nice work on this repo :+1:

**Comment by rakarmp** [comment]
Thank you @ZeinBarhoum
